### ISSUE TITLE
Deploy does not fail when required property `server_cert_domain_san` is not configured

### ISSUE THREAD

**Issue by njbennett** [cloudfoundry/routing-release#146]
Thanks for submitting an issue to `routing-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

We recently had to change UAA's route registration from `port` to `tls_port.` We missed that we also needed to provide `server_cert_domain_san` and had to spend several hours debugging. If the BOSH deploy had failed when missing this required configuration, we would have been able to fix this problem immediately.

**Comment by tylerschultz** [comment]
I assume this is a problem you saw with the `route_registrar` job?

**Comment by njbennett** [comment]
Yep yep.

We were deploying with this configuration:

```
      route_registrar:
        routes:
        - health_check:
            name: uaa-healthcheck
            script_path: /var/vcap/jobs/uaa/bin/health_check
          name: uaa
          registration_interval: 10s
          tags:
            component: uaa
          tls_port: 8443
          uris:
          - uaa.uaa-acceptance.cf-app.com
          - '*.uaa.uaa-acceptance.cf-app.com'
          - login.uaa-acceptance.cf-app.com
          - '*.login.uaa-acceptance.cf-app.com'
```

Which doesn't work until you add
```
      server_cert_domain_san: uaa.service.cf.internal
```

and it fails in a pretty mysterious way-- complaining that the cert san doesn't include the IP address.
