### ISSUE TITLE
Stale Routes in gorouters

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/routing-release#149]
Thanks for submitting an issue to `cf-networking-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

We have several issues where we are getting "stale" routes in the gorouters that are NOT being pruned.

## Context

We are not really sure where this should go.  Basically what happens is we get a route registered and then the app moves.  But then a second app will reuse the port on the same cell but with the NON-TLS endpoint (8080) etc.  This when the gorouter communicates to the cell will NOT produce a correct prune and we get a 502 error instead.

## Steps to Reproduce

I think you will need to force this to test how it should correctly prune it and why there is no TLS error which should cause the prune

## Expected result

When there is no TLS connection the routes should be pruned from the gorouters.

## Current result

We have seen this many times and it causes a lot of problems in production as we get 502s when the connection is not correctly prunes.

If this is not the correct place for this can you please let us know whether it needs to be in silk or routing or cf-networking.

I just picked here as we seem to own all of the networking issues.

**Comment by andrew-edgar** [comment]
Here is the gorouter definition.   This is on cfd 6.8.0 and routing-release 0.188.0

```
  - name: gorouter
    properties:
      router:
        backends:
          cert_chain: ((/secrets/gorouter_backend_tls/v2.certificate))
          private_key: ((/secrets/gorouter_backend_tls/v2.private_key))
        ca_certs: |
          ((/secrets/application_ca/v2.certificate))
          ((/secrets/ibmCFcacert/v2.certificate))
        droplet_stale_threshold: 200s
        enable_ssl: true
        endpoint_timeout: 120
        extra_headers_to_log:
        - x-global-transaction-id
        - True-Client-IP
        isolation_segments: []
        logging_level: error
        max_idle_connections: 49000
        prune_stale_droplets_interval: 90s
        requested_route_registration_interval_in_seconds: 50
        route_services_recommend_https: "true"
        route_services_secret: ((/secrets/router_route_service_secret/v1))
        route_services_timeout: null
        routing_table_sharding_mode: all
        skip_oauth_tls_verification: true
        status:
          password: ((/secrets/router_password/v1))
          port: 8080
          user: ((/secrets/router_user/v1))
        suspend_pruning_if_nats_unavailable: true
        tls_pem:
        - cert_chain: ((/secrets/router_tls_pem/v2.certificate))
          private_key: ((/secrets/router_tls_pem/v2.private_key))
        tracing:
          enable_zipkin: true
      routing_api:
        enabled: false
      uaa:
        ca_cert: ((/secrets/ibmCFcacert/v2.certificate))
        clients:
          gorouter:
            secret: ((/secrets/router_password/v1))
        ssl:
          port: 8443
    release: routing
```
