### ISSUE TITLE
Compilation of 0.263.0 fails on Xenial and Jammy

### ISSUE THREAD

**Issue by MirahImage** [cloudfoundry/routing-release#319]
## Issue
Bosh fails to compile the acceptance_tests package with the following error:
```
Error: Action Failed get_task: Task 920b50d9-7c76-485c-4865-2d36b57aa88a result: Compiling package acceptance_tests: Running packaging script: Running packaging script: Command exited with 1; Stdout: /var/vcap/packages/acceptance_tests/src/code.cloudfoundry.org /var/vcap/packages/acceptance_tests /var/vcap/data/compile/acceptance_tests
, Stderr: + mkdir -p /var/vcap/packages/acceptance_tests/src
+ cp -a . /var/vcap/packages/acceptance_tests/src
+ pushd /var/vcap/packages/acceptance_tests
+ source /var/vcap/packages/golang-1.20-linux/bosh/compile.env
++ '[' -z '' ']'
+++ readlink -nf /var/vcap/packages/golang-1.20-linux
++ export GOROOT=/var/vcap/data/packages/golang-1.20-linux/46c4b5557ce440c23ca2b72a5f332ce60ab9e61f
++ GOROOT=/var/vcap/data/packages/golang-1.20-linux/46c4b5557ce440c23ca2b72a5f332ce60ab9e61f
++ export GOPATH=/var/vcap/packages/acceptance_tests
++ GOPATH=/var/vcap/packages/acceptance_tests
++ export GOCACHE=/var/vcap/data/golang-1.20-linux/cache
++ GOCACHE=/var/vcap/data/golang-1.20-linux/cache
++ export PATH=/var/vcap/data/packages/golang-1.20-linux/46c4b5557ce440c23ca2b72a5f332ce60ab9e61f/bin:/var/vcap/packages/acceptance_tests/bin:/var/vcap/bosh/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin
++ PATH=/var/vcap/data/packages/golang-1.20-linux/46c4b5557ce440c23ca2b72a5f332ce60ab9e61f/bin:/var/vcap/packages/acceptance_tests/bin:/var/vcap/bosh/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin
+ pushd src/code.cloudfoundry.org
+ go install github.com/onsi/ginkgo/ginkgo
go: finding module for package github.com/onsi/ginkgo/ginkgo
cannot query module due to -mod=vendor
	(Go version in go.mod is at least 1.14 and vendor directory exists.)
```

## Affected Versions
0.263.0

## Steps to Reproduce

1. Upload release to a bosh director `bosh upload-release`
2. Create empty deployment using routing release `bosh -d routing-compilation deploy manifest.yml`
  manifest.yml:
```yaml
---
name: routing-compilation

releases:
  - name: routing-release
    version: 0.263.0

stemcells:
- alias: jammy # xenial also has this problem
  os: ubuntu-jammy
  version: latest

update:
  canaries: 5
  canary_watch_time: 30000-180000
  max_in_flight: 5
  update_watch_time: 30000-180000

instance_groups: []
```
3. Export compiled release `bosh export-release routing-release/0.263.0 ubuntu-jammy/1.105`

## Expected result

Successful compiled release tarball

## Current result

Bosh is unable to compile the release with the error above.
