### ISSUE TITLE
Session Affinity not working

### ISSUE THREAD

**Issue by sterankin** [cloudfoundry/routing-release#369]
## Issue
Session Affinity/Sticky sessions are not working.

## Context

I have added the following section `sticky_session_cookie_names` to the manifest file which looks something like:

```
applications:
  - name: myapp
    routes:
      - route: ${name}.us-east-1.np.com
    instances: 2
    memory: 4096M
    timeout: 600
    router:
      sticky_session_cookie_names: [ "_myapp_session" ]
    buildpacks:
      - ruby
    stack: cflinuxfs3
    env:
```

## Traffic Diagram 

```

           +----+---+    +----------+     +-------+
  \o/      |        |    |          |     |       |
   +  +--->+ AWS LB +--->+ Gorouter +---->+  App  |
  / \      |        |    |          |     |       |
 client    +--------+    +----------+     +-------+
```

## Expected result

I would expect session affinity to work and the VCAP_ID to be visible in the headers or cookie as per:
https://docs.cloudfoundry.org/concepts/http-routing.html#sessions

## Current result
There is no VCAP_ID in the cookies and the user is still redirected to different instances of the app

## Additional Context
Since this is a Ruby on Rails app, we are setting the session store as follows when the app initialises.  I assume this has to match the `sticky_session_cookie_names` set in the manifest.

`Rails.application.config.session_store :cookie_store, key: '_myapp_session'`
