### ISSUE TITLE
An issue with 'client_cert_validation: require'

### ISSUE THREAD

**Issue by georgibarzev** [cloudfoundry/routing-release#92]
Hi,

I'm trying the scenario where there are a couple of routers set to `client_cert_validation: require` and ELB is configured to use those routers for a particular app domain that needs to force mTLS. The problem is that when providing a wrong cert I can still see the page (no cert provided seems to correctly lead to a cert issue denying the page). I'm facing the same issue when all routers are centrally configured with `properties.router.client_cert_validation: require`.

The relevant parts of the manifest used look like this, please let me know if there are other dependencies:

```
- instances: 1
  name: router_z1
  properties:
    router:
      client_cert_validation: require

- instances: 1
  name: router_z2
  properties:
    router:
      client_cert_validation: require
    
- instances: 1
  name: router_z3
  properties:
    router:
      client_cert_validation: request
    
properties:
  router:
    cipher_suites: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384:TLS_RSA_WITH_AES_128_CBC_SHA
    ca_certs: |
      -----BEGIN CERTIFICATE-----
 
      -----END CERTIFICATE-----
    disable_http: true
    enable_ssl: true
    forwarded_client_cert: sanitize_set
    min_tls_version: TLSv1.1
    ssl_skip_validation: false
```

The router_z1 also keeps returning these type of repeating messages: `tls: client offered an unsupported, maximum protocol version of 301`, `remote error: tls: bad certificate`, `tls: client didn't provide a certificate`, though not necessarily corresponding to me hitting the page on the browser. Any ideas?

Thanks and Regards,
Georgi
